cache_directory = "/var/cache/cpcache"

# Bind to an IPv6 address, in addition to an IPv4 address.
ipv6_enabled = true

# cpcache will routinely purge old packages. This parameter specifies how many
# versions should be kept in the cache before purging.
# Set to 0 to disable this behavior.
keep = 3

[x86]
    # Enter the URL of the mirror currently used in /etc/pacman.d/mirrorlist
    # here, WITHOUT trailing $repo/os/$arch.
    url = "https://mirror.js-webcoding.de/pub/archlinux/"
    port = 7070
    # Note that cpcache relies on the directory structure that is created in
    # /var/cache/cpcache during install. If you change this setting, copy the
    # contents to the new directory and make sure user cpcache has read- and
    # write-access.

# If one of your clients runs on Arch Linux ARM, uncomment the following:
# [arm]
#     url = "http://mirror.archlinuxarm.org"
#     port = 7080

[recv_packages]
    key = "topsecret"
